param(
    [Parameter(Mandatory)][string]$OutputDirectory,
    [ValidateSet('Release')][string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$outputPath = [IO.Path]::GetFullPath($OutputDirectory)
$projectPath = Join-Path $repositoryRoot 'src/IdentityIssuer/IdentityIssuer.csproj'
$repositoryPath = [IO.Path]::GetFullPath($repositoryRoot).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar

if ($outputPath.StartsWith($repositoryPath, [StringComparison]::OrdinalIgnoreCase) -or
    $outputPath.Equals($repositoryPath.TrimEnd([IO.Path]::DirectorySeparatorChar), [StringComparison]::OrdinalIgnoreCase)) {
    throw 'Choose a deployment output directory outside the source checkout.'
}

dotnet publish $projectPath -c $Configuration --no-self-contained -o $outputPath
if ($LASTEXITCODE -ne 0) {
    throw "Issuer publish failed with exit code $LASTEXITCODE."
}

if (-not (Test-Path -LiteralPath (Join-Path $outputPath 'web.config'))) {
    throw 'The ASP.NET Core Module web.config was not generated by publish.'
}

Write-Output "Published issuer files to $outputPath"
Write-Output 'The publish output contains no signing or encryption private keys; configure those on the target server.'
